minimum_pre_commit_version: "4.4.0"

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --project django_version ruff check --fix
        language: unsupported
        types_or: [python, pyi]
        files: ^django_version/

      - id: ruff-format
        name: ruff format
        entry: uv run --project django_version ruff format
        language: unsupported
        types_or: [python, pyi]
        files: ^django_version/
