# Generated by Django 6.0.3 on 2026-05-25 15:30

from django.db import migrations

SKILLS_TO_SEED = [
    {"name": "Python", "category": "TECHNOLOGY"},
    {"name": "JavaScript", "category": "TECHNOLOGY"},
    {"name": "TypeScript", "category": "TECHNOLOGY"},
    {"name": "PHP", "category": "TECHNOLOGY"},
    {"name": "C#", "category": "TECHNOLOGY"},
    {"name": "C/C++", "category": "TECHNOLOGY"},
    {"name": "HTML/CSS", "category": "TECHNOLOGY"},
    {"name": "Java", "category": "TECHNOLOGY"},
    {"name": "UI/UX Design", "category": "DESIGN"},
    {"name": "Figma", "category": "DESIGN"},
    {"name": "Graphic Design", "category": "DESIGN"},
    {"name": "Logo Design", "category": "DESIGN"},
    {"name": "Adobe Illustrator", "category": "DESIGN"},
    {"name": "Web Design", "category": "DESIGN"},
    {"name": "Brand Identity", "category": "DESIGN"},
    {"name": "Motion Graphics", "category": "DESIGN"},
    {"name": "Copywriting", "category": "WRITING"},
    {"name": "Content Writing", "category": "WRITING"},
    {"name": "Technical Writing", "category": "WRITING"},
    {"name": "SEO Writing", "category": "WRITING"},
    {"name": "Proofreading", "category": "WRITING"},
    {"name": "Creative Writing", "category": "WRITING"},
    {"name": "Translation", "category": "WRITING"},
    {"name": "Digital Marketing", "category": "MARKETING"},
    {"name": "Social Media Management", "category": "MARKETING"},
    {"name": "SEO Optimization", "category": "MARKETING"},
    {"name": "Email Marketing", "category": "MARKETING"},
    {"name": "Content Marketing", "category": "MARKETING"},
    {"name": "Search Engine Marketing", "category": "MARKETING"},
    {"name": "Google Analytics", "category": "MARKETING"},
]


def seed_skills(apps, schema_editor):
    Skill = apps.get_model("profiles", "Skill")
    skills = [
        Skill(name=skill["name"], category=skill["category"])
        for skill in SKILLS_TO_SEED
    ]
    Skill.objects.bulk_create(skills, ignore_conflicts=True)


def remove_skills(apps, schema_editor):
    Skill = apps.get_model("profiles", "Skill")
    names = [skill["name"] for skill in SKILLS_TO_SEED]
    Skill.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_skills, remove_skills),
    ]
