# Generated by Django 6.0.3 on 2026-05-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staffuser_is_staff'),
        ('profiles', '0002_seed_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short user biography (max 500 characters)', max_length=500, verbose_name='Biography')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user profile was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the user profile was last updated', verbose_name='Updated At')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text="Hourly rate of the freelancer in the platform's base currency.", max_digits=8, verbose_name='Hourly Rate')),
                ('portfolio_url', models.URLField(blank=True, help_text="Link to the freelancer's external portfolio site. Optional, but cannot be blank if provided.", verbose_name='Portfolio URL')),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Number of years of professional experience the freelancer has.', verbose_name='Years of Experience')),
                ('skills', models.ManyToManyField(blank=True, help_text='Skills associated with this freelancer. At least one is required.', to='profiles.skill', verbose_name='Skills')),
                ('user', models.OneToOneField(help_text='The freelancer user associated with this profile.', on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='accounts.freelancer', verbose_name='Freelancer')),
            ],
            options={
                'verbose_name': 'Freelancer Profile',
                'verbose_name_plural': 'Freelancer Profiles',
                'db_table': 'freelancer_profiles',
            },
        ),
    ]
