# Generated by Django 6.0.6 on 2026-07-10 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_freelancerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freelancerprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Short user biography (max 500 characters)",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
                verbose_name="Biography",
            ),
        ),
    ]
