# Generated by Django 6.0.6 on 2026-07-17 14:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staffuser_staffuser_active_no_staff_status'),
        ('profiles', '0005_alter_freelancerprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short user biography (max 500 characters)', max_length=500, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Biography')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user profile was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the user profile was last updated', verbose_name='Updated At')),
                ('company_name', models.CharField(blank=True, help_text="Name of the client's company.", max_length=200, verbose_name='Company Name')),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget the client is willing to pay for a project.', max_digits=10, null=True, verbose_name='Maximum Budget')),
                ('website_url', models.URLField(blank=True, help_text="Link to the client's or company's external website. Optional, must be a valid URL if provided.", verbose_name='Website URL')),
                ('interests', models.ManyToManyField(blank=True, help_text='Professional areas of interest or skills that the client is looking for.', to='profiles.skill', verbose_name='Interests')),
                ('user', models.OneToOneField(help_text='The client user associated with this profile.', on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='accounts.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'db_table': 'client_profiles',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
