# Generated by Django 6.0.7 on 2026-08-06 12:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_clientprofile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='skill_unique_name_case_insensitive'),
        ),
    ]
