# Generated by Django 6.0.3 on 2026-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffuser",
            name="is_staff",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the user can log into the Django admin site",
                verbose_name="Staff Status",
            ),
        ),
    ]
