# Generated by Django 6.0.6 on 2026-06-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_staffuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freelancer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Freelancer', 'verbose_name_plural': 'Freelancers'},
        ),
    ]
