# Generated by Django 6.0.6 on 2026-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staffuser_is_staff'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='freelancer',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('is_available', True), _negated=True), name='freelancer_no_inactive_available'),
        ),
    ]
